#!/usr/bin/perl

use strict;
use warnings;

my $admin = 'sudo -u riak /usr/sbin/riak-admin';
my $join_ip = shift || die "Usage: $0 JOIN_IP\n";
my $conn    = `$admin status | grep -i connected_nodes | grep "33.10"`;

exit 0 if $conn;
my $cluster = "$admin cluster";

exit(system "$cluster join riak\@$join_ip; $cluster plan; $cluster commit");

__END__
