#!/usr/bin/perl

use strict;
use warnings;

my $join_ip = shift || die "Usage: $0 JOIN_IP\n";
my $conn    = `sudo -u riak /usr/sbin/riak-admin status | grep -i connected_nodes | grep "33.10"`;

exit 0 if $conn;

exit(system "sudo -u riak /usr/sbin/riak-admin cluster join riak\@$join_ip");

__END__
